### ISSUE TITLE
KeyError: 'chunks_centroids' during MIDAS database initialization

### ISSUE THREAD

**Issue by zfsh** [czbiohub-sf/MIDAS#141]
Dear Developer,
When I attempt to initialize the MIDAS database using the `--init` command, I encounter a `KeyError: 'chunks_centroids'`.
Here are the details:
(midasv3) lenovo@lenovo-ThinkStation:~/software/MIDAS-3$ midas database --init --midasdb_name uhgg --midasdb_dir my_midasdb_uhgg/
1720838073.1: Initate MIDASDB uhgg to my_midasdb_uhgg/::start
1720838142.8: Initate MIDASDB uhgg to my_midasdb_uhgg/::finish
1720838142.8: Download chunks for MIDASDB uhgg to my_midasdb_uhgg/::start
Traceback (most recent call last):
File "/home/lenovo/anaconda3/envs/midasv3/bin/midas", line 10, in <module>
sys.exit(main())
File "/home/lenovo/anaconda3/envs/midasv3/lib/python3.9/site-packages/midas/main.py", line 25, in main
return subcommand_main(subcommand_args)
File "/home/lenovo/anaconda3/envs/midasv3/lib/python3.9/site-packages/midas/subcommands/database.py", line 146, in main
init_midasdb(args)
File "/home/lenovo/anaconda3/envs/midasv3/lib/python3.9/site-packages/midas/subcommands/database.py", line 29, in init_midasdb
midasdb.fetch_files("chunks")
File "/home/lenovo/anaconda3/envs/midasv3/lib/python3.9/site-packages/midas/models/midasdb.py", line 190, in fetch_files
return self.fetch_tarball(filename, list_of_species)
File "/home/lenovo/anaconda3/envs/midasv3/lib/python3.9/site-packages/midas/models/midasdb.py", line 251, in fetch_tarball
_fetched_file = self.get_target_layout(ct, False, sid, gid, DEFAULT_CHUNKS[i])
File "/home/lenovo/anaconda3/envs/midasv3/lib/python3.9/site-packages/midas/models/midasdb.py", line 165, in get_target_layout
local_path = self.construct_local_path(filename, species_id, genome_id, component)
File "/home/lenovo/anaconda3/envs/midasv3/lib/python3.9/site-packages/midas/models/midasdb.py", line 152, in construct_local_path
local_path = _get_local_path(get_midasdb_layout(species_id, genome_id, component)[filename], self.db_dir)
KeyError: 'chunks_centroids'

I can make sure that my midasv3 environment is installed and I have successfully run _test_analysis.sh_ and _test_db.sh_. According to _test_db.sh_, I should have pre-downloaded the midasdb, but when I use the commands in the midas2 User manual to download the database, I always get this problem. How can I solve this problem.
Thanks a lot!

**Comment by zhaoc1** [comment]
Hi,

test_db.sh is for testing building custom MIDASDB, and it doesn't mean you have downloaded the midasdb.  

Despite that, I fixed midas database init and please re-install midas 3.0.1. 

Thanks.
Chunyu

**Comment by zfsh** [comment]
Hi Chunyu,

Thank you very much for your help and clarification. I have reinstalled MIDAS 3.0.1 as you suggested, and everything is running smoothly now.

I really appreciate your support. Wishing you all the best in your work!
