### ISSUE TITLE
Error when generating pruned centroids sequences for species of interests.

### ISSUE THREAD

**Issue by michaelwasney** [czbiohub-sf/MIDAS#142]
I am getting an error when I try to prune centroid sequences for a species of interest.

I am processing sample1 and sample2 fastqs contained in this repository. I have successfully (1) downloaded the uhgg midasdb, (2) processed each sample using the run_species command, and (3) merged species outputs across samples. 

This is the merged species output:

species_id	sample1	sample2
102340	6.358	0.000
102454	6.341	6.330
101921	0.214	0.214
102478	0.000	6.015

I attempt to prune the centroids for species 102340 using the following command:

```
midas prune_centroids --midasdb_name uhgg --midasdb_dir /u/scratch/m/michaelw/my_midasdb_uhgg -t 1 --remove_singleton --species 102340 --force --debug
```
And I get the following output/error:

```
1722973109.6:  Executing midas subcommand prune_centroids with args
1722973109.6:  {
1722973109.6:      "subcommand": "prune_centroids",
1722973109.6:      "force": true,
1722973109.6:      "debug": true,
1722973109.6:      "zzz_worker_mode": false,
1722973109.6:      "batch_branch": "master",
1722973109.6:      "batch_memory": 378880,
1722973109.6:      "batch_vcpus": 48,
1722973109.6:      "batch_queue": "pairani",
1722973109.6:      "batch_ecr_image": "pairani:latest",
1722973109.6:      "species": "102340",
1722973109.6:      "midasdb_name": "uhgg",
1722973109.6:      "midasdb_dir": "/u/scratch/m/michaelw/my_midasdb_uhgg",
1722973109.6:      "num_threads": 1,
1722973109.6:      "scratch_dir": ".",
1722973109.6:      "prune_method": "max",
1722973109.6:      "prune_cutoff": 0.4,
1722973109.6:      "remove_singleton": true
1722973109.6:  }
1722973110.7:  Pruning centorids_99 sequences for species 102340 with 26 total genomes.
Traceback (most recent call last):
  File "/u/home/m/michaelw/.conda/envs/midasv3/bin/midas", line 10, in <module>
    sys.exit(main())
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/__main__.py", line 25, in main
    return subcommand_main(subcommand_args)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/subcommands/prune_centroids.py", line 209, in main
    prune_centroids(args)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/subcommands/prune_centroids.py", line 108, in prune_centroids
    prune_centroids_master(args)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/subcommands/prune_centroids.py", line 167, in prune_centroids_master
    multithreading_map(species_work, species_id_list, args.num_threads)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/common/utils.py", line 540, in multithreading_map
    return _multi_map(func, items, num_threads, ThreadPool)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/common/utils.py", line 520, in _multi_map
    return p.map(func, items, chunksize=1)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/subcommands/prune_centroids.py", line 158, in species_work
    command(worker_cmd)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/common/utils.py", line 246, in command
    return subprocess.run(cmd, shell=shell, **subproc_args)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd /u/scratch/m/michaelw/my_midasdb_uhgg/pangenomes/102340/pruned; PYTHONPATH=/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages /u/home/m/michaelw/.conda/envs/midasv3/bin/python -m midas prune_centroids -s 102340 --zzz_worker_mode -t 1 --prune_method max --prune_cutoff 0.4 --remove_singleton --midasdb_name uhgg --midasdb_dir /u/scratch/m/michaelw/my_midasdb_uhgg --debug --scratch_dir . &>> /u/scratch/m/michaelw/my_midasdb_uhgg/pangenomes/102340/pruned/pangenome_prune.log' returned non-zero exit status 1.
```

Here are the contents of`/u/scratch/m/michaelw/my_midasdb_uhgg/pangenomes/102340/pruned/pangenome_prune.log`:

```
Pruning centorids_99 sequences for species 102340 with 26 total genomes.
cd /u/scratch/m/michaelw/my_midasdb_uhgg/pangenomes/102340/pruned; PYTHONPATH=/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages /u/home/m/michaelw/.conda/envs/midasv3/bin/python -m midas prune_centroids -s 102340 --zzz_worker_mode -t 1 --prune_method max --prune_cutoff 0.4 --remove_singleton --midasdb_name uhgg --midasdb_dir /u/scratch/m/michaelw/my_midasdb_uhgg --debug --scratch_dir . &>> /u/scratch/m/michaelw/my_midasdb_uhgg/pangenomes/102340/pruned/pangenome_prune.log
1722973112.1:  Executing midas subcommand prune_centroids with args
1722973112.1:  {
1722973112.1:      "subcommand": "prune_centroids",
1722973112.1:      "force": false,
1722973112.1:      "debug": true,
1722973112.1:      "zzz_worker_mode": true,
1722973112.1:      "batch_branch": "master",
1722973112.1:      "batch_memory": 378880,
1722973112.1:      "batch_vcpus": 48,
1722973112.1:      "batch_queue": "pairani",
1722973112.1:      "batch_ecr_image": "pairani:latest",
1722973112.1:      "species": "102340",
1722973112.1:      "midasdb_name": "uhgg",
1722973112.1:      "midasdb_dir": "/u/scratch/m/michaelw/my_midasdb_uhgg",
1722973112.1:      "num_threads": 1,
1722973112.1:      "scratch_dir": ".",
1722973112.1:      "prune_method": "max",
1722973112.1:      "prune_cutoff": 0.4,
1722973112.1:      "remove_singleton": true
1722973112.1:  }
Traceback (most recent call last):
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/__main__.py", line 29, in <module>
    main()
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/__main__.py", line 25, in main
    return subcommand_main(subcommand_args)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/subcommands/prune_centroids.py", line 209, in main
    prune_centroids(args)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/subcommands/prune_centroids.py", line 106, in prune_centroids
    prune_centroids_worker(args)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/midas/subcommands/prune_centroids.py", line 181, in prune_centroids_worker
    c75_info = pd.read_csv(local_file(midas_db, species_id, "75"), sep="\t")
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/u/home/m/michaelw/.conda/envs/midasv3/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/u/scratch/m/michaelw/my_midasdb_uhgg/pangenomes/102340/clusters_75_info.tsv'
```

Can you help me resolve this issue? Thank you in advance!

**Comment by zhaoc1** [comment]
Hi,

The error messages `FileNotFoundError: [Errno 2] No such file or directory: '/u/scratch/m/michaelw/my_midasdb_uhgg/pangenomes/102340/clusters_75_info.tsv'` is accurate.

The MIDASDB for downloading only have the minimal necessary files for `run_genes` and `merge_genes`, and `clusters_75_info.tsv` is not one of them. I decided to include the post-pruned centroids_99 instead, using the default `--prune_method`,  `--prune_cutoff`, `--remove_singleton `.  Since your `prune_centroids` is using the default parameters, the post-pruned centroids should be already under `{species_id}/pruned/centroids_by.max.0.4.rmsig.ffn`. If not, please let me know.

If you want to perform a different set of pruning, let me an message, and I will figure out a way to share the full MIDASDB, which is much larger though.

Hope this helps.
Chunyu

**Comment by michaelwasney** [comment]
Hi Dr. Zhao,

Thank you for your guidance! 

I looked in `/u/scratch/m/michaelw/my_midasdb_uhgg/pangenomes/102340/pruned/` (102340 is the species_id), and there was no file called  `centroids_by.max.0.4.rmsig.ffn`. Is that a file that should be produced by `prune_centroids` using default parameters? And if so, where would I find it, if not in `pangenomes/102340/pruned/`

Additionally, can you provide me with an example of the code I need to execute if it is not what is in the README.md of this repository (i.e., `midas prune_centroids --midasdb_name localdb --midasdb_dir /path/to/midasdb-uhgg-v2 -t 1 --remove_singleton --species 100001 --force --debug`).

Thanks again for your help!

Best,
Michael

**Comment by zhaoc1** [comment]
Hi,

I was actually wrong about the `clusters_info_75.tsv`.  It is indeed included in the default MIDASDB v3; it was not included for MIDAS2.

A quick check would be `wget https://midasdb.pollard.gladstone.org/v3/uhgg/pangenomes/100001.tar.gz`

Can you make sure you update MIDAS to v3, and delete and re-download the MIDASDB?

Thanks.
Chunyu

**Comment by michaelwasney** [comment]
Hi Dr. Zhao,

I am already using MIDAS v3. E.g., when I execute `midas --version', I get:

```
Metagenomic Intra-Species Diversity Analysis System (MIDAS), Version 3.0.1
```

Using MIDAS v3, I download the MIDASdb like so:

```
midas database --init --midasdb_name uhgg --midasdb_dir my_midasdb_uhgg/
```

Given that the issue is not that I'm using MIDAS v2, might there be some other issue to resolve my issue? Is the solution that I have to download individual reference pangenomes for every species of interest (e.g., by executing wget `https://midasdb.pollard.gladstone.org/v3/uhgg/pangenomes/100001.tar.gz`)?

**Comment by zhaoc1** [comment]
Ohh I see. Thanks for sharing the command.  Basically `midas database --init` only set up the file system for MIDASDB. In order to download the MIDASDB, you need to run `midas database--download`. You are refer to [ReadTheDoc: download MIDASDB](https://midas2.readthedocs.io/en/latest/download_midasdb.html).  This should download the ENTIRE MIDASDB for either UHGG for GTDB (depends on the --midasdb_name). You won't need to run the wget command, it is already wrapped inside the `--download` step. 

Sorry for the confusion. 
Best
Chunyu

**Comment by michaelwasney** [comment]
Oh, thank you! Apologies, I think I missed that section of the the documentation. Many thanks!

**Comment by zhaoc1** [comment]
Glad to help. No worries. Thanks for using MIDAS. :)
